#!/bin/bash

if [ -z "${WORKSPACE}" ]; then
    WORK_DIR="${TRAVIS_BUILD_DIR}"
    export WORK_DIR
elif [ -e "${WORKSPACE}" ]; then
    WORK_DIR="${WORKSPACE}"
    export WORK_DIR
else
    echo "Unknown workspace."
    exit 1
fi

if [ -d "${WORK_DIR}/.kcov" ]; then
    export PATH="${WORK_DIR}/.kcov/bin:$PATH"
else
    echo "Could not find kcov."
    exit 1
fi

set -eu

# Generate coverage files

echo "INFO: Generating coverage.."
for file in target/debug/xtc-*; do
    printf "Generating coverage for file: %s\n" "${file}"
    mkdir -p "target/cov/$(basename "$file")"
    kcov --exclude-pattern=/.cargo,/usr/lib \
         --verify "target/cov/$(basename "$file")" \
         "$file"
done
