#!/bin/bash

set -eu

export WORK_DIR="${TRAVIS_BUILD_DIR}/rust"
export PATH="$HOME/.cargo/bin:$PATH"

if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then
    ( (
        cargo install clippy \
            && \
            export CLIPPY=true ) \
          || export CLIPPY=false \
    )
fi

if [[ "${TRAVIS_RUST_VERSION}" == "nightly" && \
          "${CLIPPY}" ]]; then \
    cargo clippy
fi

cd "${WORK_DIR}" 

make ci-check

exit
