#!/bin/bash

set -eu

export WORK_DIR="${TRAVIS_BUILD_DIR}/rust"
export PATH="$HOME/.cargo/bin:$PATH"

export CLIPPY=false
if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then
    cargo install --force clippy && CLIPPY=true
fi

if [[ "${TRAVIS_RUST_VERSION}" == "nightly" && \
          "${CLIPPY}" ]]; then \
    cargo clippy
fi

cd "${WORK_DIR}" 

make ci-check

exit
