#!/bin/bash

if [[ -n "${TRAVIS_BUILD_DIR}" ]]; then
    export WORK_DIR="${TRAVIS_BUILD_DIR}/rust"
elif [[ -n "${WORKSPACE}" ]]; then
    export WORK_DIR="${WORKSPACE}/rust"
else
    echo "Unknown workspace."
    exit 1
fi

set -eu

# shellcheck source=/dev/null
. "${PWD}/script/utils.sh"

export PATH="$WORK_DIR/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

cd "${WORK_DIR}" 

make ci-check

exit
