#!/bin/sh -eu

source "${PWD}/script/utils.sh"

echo -e "${GREEN}INFO:${RESET} Outputting list of contributors.."

OUTPUT="$(git shortlog -sne)"

echo "${OUTPUT}" > AUTHORS

echo -e "${GREEN}INFO:${RESET} ..Complete."

exit
