#!/bin/bash -eu

# shellcheck source=/dev/null
. "${PWD}/script/utils.sh"

echo -e "${GREEN}INFO:${RESET} Outputting list of contributors.."

git shortlog -sne > AUTHORS

echo -e "${GREEN}INFO:${RESET} ..Complete."

git add AUTHORS
git commit -m "Update AUTHORS file"

exit
